Create install_fenics-hpc_0.8.4-intel-2016-impi-5.1.3.223.sh
MSO4SC/fenics-hpc-cesga pull request #5
Opened 2017-05-29 08:19 UTC by victorsndvg

Install fenics-hpc with intel compilers

2017-05-31 13:27 UTC, emepetres requested changes
Please Victor could you also update the README to explain a little bit about this file and how it should be used (e.g. instead of the actual install file, is a complement, an improvement over the previous one?)

2017-05-31 15:26 UTC, victorsndvg commented
Ok @emepetres ,

Is a new installation of FEniCS-HPC with intel compilers and using another installation of PETSc library in order to get better performance.

Ok, I agree with you :+1:   I will create a folder with a README.md file and some scripts to run the cube demo with this new installation ASAP.

2017-06-06 10:28 UTC, victorsndvg commented
Hi @emepetres ,

I've added some scripts and change the *README.md* scripts.

The wiki document was also updated.

Let me know if this changes are OK for you

2017-06-06 17:15 UTC, emepetres approved these changes

2017-06-06 17:16 UTC, merged